name: TF Linter Check
on:
  push:
    branches-ignore: [master, main, UnitOfWork]
  pull_request:
    branches: [master, main, UnitOfWork]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_MD: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_TERRAFORM_TFLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
